apiVersion: apps/v1
kind: Deployment
metadata:
  name: forkub-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: forkub
  template:
    metadata:
      labels:
        app: forkub
    spec:
      containers:
        - name: forkub-container
          image: borissolomonia/forkub-1:tagname
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
---

apiVersion: v1
kind: Service
metadata:
  name: forkub-service
  labels:
    name: forkub-service
    app: forkub
spec:
  type: LoadBalancer
  selector:
    name: forkub-pod
    app: forkub
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
